baseURL = "https://taejun864.github.io/portfolio/"
languageCode = "ko-KR"
title = "Lee Taejun"
theme = "personal-web"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true
defaultContentLanguage = 'ko'
defaultContentLanguageInSubdir = true

[params.intro]
  main = "이태준"
  sub = "저는 4년 6개월 경력의 IT 엔지니어입니다."

[params.main]
  latestPublishHeader = "최근 프로젝트"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio']

[params.notFound]
  gopher = "/portfolio/images/gopher.png"
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/portfolio/images/safar-safarov-koOdUvfGr4c-unsplash.jpg'
  gradientOverlay = ''
  logo = "/portfolio/images/taejun.jpg"

[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/taejun864"
  twitter = false
  linkedin = "https://www.linkedin.com/in/taejun-lee-172302300/"
  medium = false
  codepen = false
  facebook = false
  youtube = false
  instagram = false
  gitlab = false
  keybase = false

[params.contact]
  email = ""
  text= ""


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/ko/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/ko/portfolio/"
  weight = -110

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[languages]
  [languages.ko]
    contentDir = 'content/ko'
    disabled = false
    languageName = '한국어'
    weight = 10
  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja-JP'
    languageName = '日本語'
    title = 'Lee Taejun'
    weight = 20
    [languages.ja.params]
      [languages.ja.params.intro]
        main = "李泰俊"
        sub = "私は4年6ヶ月の経歴のITエンジニアです。"
      [languages.ja.params.main]
        latestPublishHeader = "最近のプロジェクト"
      [languages.ja.menu]
        [[languages.ja.menu.main]]
          identifier = "about"
          name = "About"
          title = "About section"
          url = "/ja/about/"
          weight = -120
        [[languages.ja.menu.main]]
          identifier = "portfolio"
          name = "Portfolio"
          title = "Portfolio"
          url = "/ja/portfolio/"
          weight = -110
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Lee Taejun'
    weight = 30
    [languages.en.params]
      [languages.en.params.intro]
        main = "LEE TAEJUN"
        sub = "I'm IT engineer who have 4 years and 6 months of exprence."
      [languages.en.params.main]
        latestPublishHeader = "Recent Project"
      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          title = "About section"
          url = "/en/about/"
          weight = -120
        [[languages.en.menu.main]]
          identifier = "portfolio"
          name = "Portfolio"
          title = "Portfolio"
          url = "/en/portfolio/"
          weight = -110